def getInd():
	out = {
		"full" : "hydrochemical refinery",
		"abbr" : "hcr",
		"number" : "33",
		"prod_cargo_types" : "DEUT,CHEM",
		"accept_cargo_types" : "HYCH",
		"prod_multiplier" : "15, 15",
		"min_cargo_distr" : "5",
		"life_type" : "PROCESSING",
		"random_sound_effects" : "",
		"conflicting_ind_types" : "",
		"input_multiplier_1" : "0",
		"input_multiplier_2" : "0",
		"input_multiplier_3" : "0",
		"spec_flags" : "",
		"prob_random" : "3",
		"prob_in_game" : "2",
		"prospect_chance" : "0",
		"fund_cost_multiplier" : "100",
		"remove_cost_multiplier" : "0",
		"tiles" : ["156","157","158","159"],
		"tile_cargos" : "[HYCH, 8]",
	}
	return out
