def getInd():
	out = {
		"full" : "xeno-flora processing",
		"abbr" : "xfp",
		"number" : "34",
		"prod_cargo_types" : "LUMB",
		"accept_cargo_types" : "WOOD",
		"prod_multiplier" : "15",
		"min_cargo_distr" : "5",
		"life_type" : "PROCESSING",
		"random_sound_effects" : "",
		"conflicting_ind_types" : "",
		"input_multiplier_1" : "0",
		"input_multiplier_2" : "0",
		"input_multiplier_3" : "0",
		"spec_flags" : "",
		"prob_random" : "3",
		"prob_in_game" : "2",
		"prospect_chance" : "0",
		"fund_cost_multiplier" : "100",
		"remove_cost_multiplier" : "0",
		"tiles" : ["160","161","162","163"],
		"tile_cargos" : "[WOOD, 8]",
	}
	return out
